config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pokemon#index"

  get '/pokemon/:id', to: 'pokemon#show', as: 'pokemon_show'
  get '/pokemon/:id/checkout', to: 'pokemon#checkout', as: 'pokemon_checkout'
  post '/pokemon/:id/buy', to: 'pokemon#buy', as: 'pokemon_buy'
  post '/pokemon/:id/sell', to: 'pokemon#sell', as: 'pokemon_sell'


  get '/user', to: 'user#index', as: 'user_index'
  get '/user/add', to: 'user#add', as: 'user_add'
  get '/user/transactions', to: 'user#transactions', as: 'user_transactions'
  patch '/user/add', to: 'user#store_money', as: 'user_store_money'




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :price, presence: true
  validates :base_experience, presence: true

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :pokemon

  OPERATIONS = {
    buy: {
        action: 'BUY'
    },
    sell: {
        action: 'SELL'
    }
  }.freeze
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pokemons, dependent: :destroy
  has_many :transactions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController

before_action :fetch_pokemon, only: [:show, :checkout, :buy, :sell]
before_action :fetch_bitcoin_price, only: [:show, :checkout, :buy, :sell]


  def index
    @pokemons = Pokemon.all
  end

  def show; end

  def checkout; end

  def buy
    handle_transaction(Transaction::OPERATIONS[:buy])
    redirect_to root_path
  end
  
  def sell
    handle_transaction(Transaction::OPERATIONS[:sell])
    redirect_to root_path
  end

  def handle_transaction(operation)

    if Transaction::OPERATIONS[:buy].equal?(operation)
      @price_in_usd = -@price_in_usd
    end

    User.transaction do
      @user = User.first
      @user.update(balance: @user.balance)
      @pokemon.update(last_sell_price: @price_in_usd)

      Transaction.new(
        action: operation[:action],
        pokemon_id: @pokemon.id,
        amount: @price_in_usd,
        user_id: @user.id
      ).save!
    end
  end

  def fetch_pokemon
    @pokemon = Pokemon.find(params[:id])
  end

  def fetch_bitcoin_price
    @price_in_usd, @btc_price = TickerService.new(pokemon_price: @pokemon.price).call
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :fetch_user

  def index
    @users = User.all
  end

  def store_money
    amount = params[:amount].values.first
    @user.update(balance: @user.balance)

    redirect_to user_index_path
  end

  def transactions
  end

  def fetch_user
    @user = User.first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokercoinBx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemon/checkout.html.erb
<h1>Pokemon#checkout</h1>


<h3><%= @pokemon.name %>'s Checkout</h3>
<p>Base Experience: <%= @pokemon.base_experience %></p>

<hr>
<p><%= @pokemon.name %>'s price': <%= @pokemon.price %></p>
<p>Bitcoin Price Today: <%= @btc_price %></p>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<p><%= button_to "Sell for USD #{@price_in_usd.round(2)}", pokemon_sell_path(@pokemon.id) %></p>

<p><%= button_to "Buy for USD #{@price_in_usd.round(2)}", pokemon_buy_path(@pokemon.id) %></p>

app/views/pokemon/index.html.erb
<h3><%= @pokemons.count %> pokemons available</h3>

<%= link_to "Operations History",  user_transactions_path %>

app/views/pokemon/show.html.erb
<h1>Pokemon#show</h1>

<h3><%= @pokemon.name %></h3>
<p>Base Experience: <%= @pokemon.base_experience %></p>



<p><%= link_to "Sell for USD #{@price_in_usd}", pokemon_checkout_path(@pokemon.id)%></p>

<p><%= link_to "Buy for BTC #{@pokemon.price}", pokemon_checkout_path(@pokemon.id)%></p>

app/views/user/add.html.erb
<%= form_tag(user_store_money_path, method: "patch") do %>
  <%= label_tag(:amount, "Please tell how much you want to deposit (0 to 10.000 USD):") %>
  <%= number_field(:amount, in: 0..10_000.00, step: 0.5) %>
  <%= submit_tag("Deposit") %>
<% end %>

app/views/user/index.html.erb
<h1>Hello, <%= @user.name %></h1>
<p>
    Your current balance is <b>USD <%= @user.balance %></b>.
    <%= link_to "Add +", user_add_path %>
</p>


<h2>Personal data</h2>
<hr>
<h4><%= @user.name %></h4>
<p><%= @user.email %></p>
<hr>
<p><%= @user.pokemons.count %> pokémon and <%= @user.transactions.count %> transactions</p>
<%= link_to "View transactions", user_transactions_path %>

<h2>Pokédex</h2>
<hr>
<table>
    <tr>
        <th>Name</th>
        <th>Base XP</th>
        <th>BuyBtn</th>
    </tr>

    <% @user.pokemons.each do |pokemon| %>
        <tr>
            <td><%= pokemon.name %></td>
            <td><%= pokemon.base_experience %></td>
            <td><%= link_to "Sell for #{pokemon.price}", pokemon_show_path(pokemon.id)%></td>
        </tr>
    <% end %>

app/views/user/transactions.html.erb
<h1>User#transactions</h1>


<hr>
<h1><%= @user.name %>'s Transactions</h1>
<table>
    <tr>
        <th>Pokemon</th>
        <th>Amount (USD)</th>
        <th>Operation</th>
        <th>Date</th>
    </tr>

    <% @user.transactions.each do |transaction| %>
        <tr>
            <td><%= transaction.pokemon.name %></td>
            <td><%= transaction.amount %></td>
            <td><%= transaction.action %></td>
            <td><%= transaction.created_at.to_s %></td>
        </tr>
    <% end %>
</table>

<%= link_to 'Back', :back %>